### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by chaidul** [chaidul/micky_layers#1]
**Path:(assets/tools/micky_font)**
Only Micky_Font navbar not responsive in reason the bootstrap framework.
Contribute this issue and fix it and share link.

**Comment by vishalpawarR** [comment]
@chaidul Hey can you please provide me the proper steps for reproducing the issue so that I can help you with this quickly? Please also provide screenshot for better understanding

**Comment by chaidul** [comment]
@vishalpawarR [https://www.mickylayers.tk/](https://www.mickylayers.tk/) 
This is my website, home page / Navbar is so good. But [https://www.mickylayers.tk/assets/tools/micky_font/index.html](https://www.mickylayers.tk/assets/tools/micky_font/index.html)
Navbar not good, this Navbar So center. Fix this navbar.
